# This file was generated by GoReleaser. DO NOT EDIT.
cask "eikona" do
  name "eikona"
  desc "Agent-first visual asset runtime and image-generation CLI."
  homepage "https://github.com/yeisme/eikona"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eikona"

  on_macos do
    on_intel do
      url "https://github.com/yeisme/eikona/releases/download/v#{version}/eikona_#{version}_Darwin_x86_64.tar.gz"
      sha256 "b02e952bac15b92b1f5d45996fbfa7416367443d72cc4e739df10e8c698fb6ff"
    end
    on_arm do
      url "https://github.com/yeisme/eikona/releases/download/v#{version}/eikona_#{version}_Darwin_arm64.tar.gz"
      sha256 "2d6207f092c03033a9dc0ea8555096b3f46f77fe8ed98b4f04148351b0430a03"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yeisme/eikona/releases/download/v#{version}/eikona_#{version}_Linux_x86_64.tar.gz"
      sha256 "75f965e661b0b716163d106cdbb0e1d230dd297db0883b8e6066ab836666fda0"
    end
    on_arm do
      url "https://github.com/yeisme/eikona/releases/download/v#{version}/eikona_#{version}_Linux_arm64.tar.gz"
      sha256 "acac8f84f2afd22097e6f377ec4418632adc360a62e6c4be8e3f35eb909c4991"
    end
  end

  # No zap stanza required
end
