# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinax" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a1bc2d5f47c81129e3fba85d04c9dd48358e4416f4a51fef9c026d24ac606ebc"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b6a84f608cb513fd9d0e3931bc8b89d4604932b25a4e480ffb435a9725939a72"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_aarch64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "542d759cd6764aad9a676cea723ae61304263b9c0fb3fc6be350be9ab79616bd"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8cd835d01ac08d2bb8b4a1b4abdd7a26194c21c9a7e8c4244291ab5b1c7cea91"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_aarch64.tar.gz"
    end
  end

  name "pinax"
  desc "Agent-safe knowledge control plane for local Markdown vaults."
  homepage "https://github.com/yeisme/pinax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinax"

  # No zap stanza required

end
