# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinax" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "6cc207c9cfc08d1f126c4323a9ba2b721af9771a4ba766e5f98dfe666c347751"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5791c0238aeec108b321de91769372a05fd7c44a465199bceb3d34b19d9e6e79"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_aarch64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d3b53df2b8580da3d42444222b19d879878a6f0e650ed9255b32b96627208f9f"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4df05f48e71e5e886867a0c92a3dae818dac40b84147d86b734c03c7deff09b9"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_aarch64.tar.gz"
    end
  end

  name "pinax"
  desc "Agent-safe knowledge control plane for local Markdown vaults."
  homepage "https://github.com/yeisme/pinax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinax"

  # No zap stanza required

end
