# This file was generated by GoReleaser. DO NOT EDIT.
cask "pinax" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "6e3114c387670b1f4ff65fced0cd6869d9ab8f1f327034563fe5b2ca16d4e77d"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6199597ee65825cc77d2bcb6dfe7a128e7ca89309de85c808342ac5ea95973c4"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_darwin_aarch64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "046328ba966b7bc1e41c7b53942e1ecbb42d0f3b7f811d086cb85e954615d1db"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "bddb8148e021998cb8001dda9f0fe18a0f613cba9cb0ac4ce075327db5473f80"
      url "https://github.com/yeisme/pinax/releases/download/v#{version}/pinax_#{version}_linux_aarch64.tar.gz"
    end
  end

  name "pinax"
  desc "Agent-safe knowledge control plane for local Markdown vaults."
  homepage "https://github.com/yeisme/pinax"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pinax"

  # No zap stanza required

end
