# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "60b791899f42b0f3eba251af54c2ba4be2a1d2b787f583bc4a7c4504298485b2"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c8c63abc15b7b4fbf46ae8eafcbcb214775706f815727165b9812397279e7249"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82286872e7b6975bee6c00368082f41d7ef902293b9696d885fd9383e00e036b"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b71b491eda114be839809d81ab2478869ff7c3935d26d322252ed3f5ac7e7594"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Manage agent skills, runtime projections, profiles, and MCP governance."
  homepage "https://github.com/yeisme/skillctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"
  bash_completion "completions/skillctl.bash"
  fish_completion "completions/skillctl.fish"
  zsh_completion "completions/skillctl.zsh"

  # No zap stanza required

end
