# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "b48ccf19ec74c4d5c1496592799d848ceb0ca6602ca848b57036eb30ae51c785"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d6e3862f1c3b1cf643b28b9210102beef2128db2622a6ad5f034193efba8488e"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "87f1fecb7c83bf363d97f982e94af93feef127b104e9ab821c5b9795af6de486"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a66788305116fa7c39d6b0b5f9668616afce31909b60a954480192c57be0a200"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Manage agent skills, runtime projections, profiles, and MCP governance."
  homepage "https://github.com/yeisme/skillctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"
  bash_completion "completions/skillctl.bash"
  fish_completion "completions/skillctl.fish"
  zsh_completion "completions/skillctl.zsh"

  # No zap stanza required

end
