# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillctl" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c9ca91467593cf0f3df845041a269125251a876834c7eca7dbae91abe427c6aa"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddcf8c880a04f46fb799278191c3c0afac6e5ed818a24803d51ee38ea23a5ca5"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "753b76e8f14d78b2cbf3468965b81bc6f3016cadf537f84353f8015e1a43ff4e"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91a7cb03bce70558a18b3497e0ff7e9f8930cdb6893e4942469028c61c05f9e8"
      url "https://github.com/yeisme/skillctl/releases/download/v#{version}/skillctl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "skillctl"
  desc "Manage agent skills, runtime projections, profiles, and MCP governance."
  homepage "https://github.com/yeisme/skillctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillctl"

  # No zap stanza required

end
