# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskbridge" do
  name "taskbridge"
  desc "TaskBridge CLI for AI-assisted multi-provider task workflows."
  homepage "https://github.com/yeisme/taskbridge"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskbridge"

  on_macos do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_x86_64.tar.gz"
      sha256 "0b386be2f2b24dd2e83e433ecd539178da5e9fea94ec3fb58215c459802ba117"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_arm64.tar.gz"
      sha256 "8d33df04489108aa505911032bcc468e5fead406ccee347e5e389a13e43444f6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_x86_64.tar.gz"
      sha256 "4056e50ec72b7b6fe316d1649b308e8f21a9cb959a03d4bdc69bb4456472f914"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_arm64.tar.gz"
      sha256 "6e612ea100bdb4c66d86b09c89c2c302ef4ec6cf850e9045f69b3ff2fa18b3cc"
    end
  end

  # No zap stanza required
end
