# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskbridge" do
  name "taskbridge"
  desc "TaskBridge CLI for AI-assisted multi-provider task workflows."
  homepage "https://github.com/yeisme/taskbridge"
  version "1.0.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskbridge"

  on_macos do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_x86_64.tar.gz"
      sha256 "4be3d668d4abe58817ae982c79ad5a1fdb4f1c048a8a53d3a3e561f6782b82ea"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_arm64.tar.gz"
      sha256 "113e58dbe35a011aef21bea86bd0d499bf3b831deb8caf405c30df4feb098ff3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_x86_64.tar.gz"
      sha256 "32981765f94762a7ef785717a5e8e923c2001c13b2e27340a1f2bcc36c934855"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_arm64.tar.gz"
      sha256 "1942f6a53bd681d4e8294c6983f48a39c15064336ac74aee7b1f589615aba680"
    end
  end

  # No zap stanza required
end
