# This file was generated by GoReleaser. DO NOT EDIT.
cask "taskbridge" do
  name "taskbridge"
  desc "TaskBridge CLI for AI-assisted multi-provider task workflows."
  homepage "https://github.com/yeisme/taskbridge"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taskbridge"

  on_macos do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_x86_64.tar.gz"
      sha256 "41325d955419c13988add2e8a44535dbbe3c92ae9d97fbaa9c8ccd7de0715ccc"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Darwin_arm64.tar.gz"
      sha256 "1f4facfaf52e1e993d90f89add6eb3349f339194160616d2ead3673ff211e65d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_x86_64.tar.gz"
      sha256 "56a414b3c2ee42a6ef465870d81e2114fd95590a5b74baf08f7687c597886b18"
    end
    on_arm do
      url "https://github.com/yeisme/taskbridge/releases/download/v#{version}/taskbridge_#{version}_Linux_arm64.tar.gz"
      sha256 "dead707212ac130de564211db63c4cf5cd8ed3e645faaad0b8cea860e37995cf"
    end
  end

  # No zap stanza required
end
