# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinax < Formula
  desc "Agent-safe knowledge control plane for local Markdown vaults."
  homepage "https://github.com/yeisme/pinax"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.0/pinax_0.1.0_darwin_x86_64.tar.gz"
      sha256 "a1bc2d5f47c81129e3fba85d04c9dd48358e4416f4a51fef9c026d24ac606ebc"

      def install
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.0/pinax_0.1.0_darwin_aarch64.tar.gz"
      sha256 "b6a84f608cb513fd9d0e3931bc8b89d4604932b25a4e480ffb435a9725939a72"

      def install
        bin.install "pinax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.0/pinax_0.1.0_linux_x86_64.tar.gz"
      sha256 "542d759cd6764aad9a676cea723ae61304263b9c0fb3fc6be350be9ab79616bd"

      def install
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.0/pinax_0.1.0_linux_aarch64.tar.gz"
      sha256 "8cd835d01ac08d2bb8b4a1b4abdd7a26194c21c9a7e8c4244291ab5b1c7cea91"

      def install
        bin.install "pinax"
      end
    end
  end

  test do
    system "#{bin}/pinax", "--help"
  end
end
