# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinax < Formula
  desc "Agent-safe knowledge control plane for local Markdown vaults."
  homepage "https://github.com/yeisme/pinax"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.1/pinax_0.1.1_darwin_x86_64.tar.gz"
      sha256 "9cc940fe58309bdfcd51e5eca4562ff1c0a8492c6bc6ae8f99ef3a7fa5e34a4b"

      def install
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.1/pinax_0.1.1_darwin_aarch64.tar.gz"
      sha256 "043cc92929db10dd2325a2c2c55e22e82bd75e3e9cd31d7a5d953ec3721f19e7"

      def install
        bin.install "pinax"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.1/pinax_0.1.1_linux_x86_64.tar.gz"
      sha256 "410b5bc08ef7ee615d546db5b496eb573ec8a82b97c7ea3e4fa277320ed576b0"
      def install
        bin.install "pinax"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.1/pinax_0.1.1_linux_aarch64.tar.gz"
      sha256 "c078fe3d0f8edbe0f610b803fd49d3859ff8170386da979e7abb7a03b2730a54"
      def install
        bin.install "pinax"
      end
    end
  end

  test do
    system "#{bin}/pinax", "--help"
  end
end
