# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pinax < Formula
  desc "Agent-safe knowledge control plane for local Markdown vaults"
  homepage "https://github.com/yeisme/pinax"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.2/pinax_0.1.2_darwin_x86_64.tar.gz"
      sha256 "6e3114c387670b1f4ff65fced0cd6869d9ab8f1f327034563fe5b2ca16d4e77d"

    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.2/pinax_0.1.2_darwin_aarch64.tar.gz"
      sha256 "6199597ee65825cc77d2bcb6dfe7a128e7ca89309de85c808342ac5ea95973c4"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.2/pinax_0.1.2_linux_x86_64.tar.gz"
      sha256 "046328ba966b7bc1e41c7b53942e1ecbb42d0f3b7f811d086cb85e954615d1db"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/pinax/releases/download/v0.1.2/pinax_0.1.2_linux_aarch64.tar.gz"
      sha256 "bddb8148e021998cb8001dda9f0fe18a0f613cba9cb0ac4ce075327db5473f80"
    end
  end

  def install
    bin.install "pinax"
  end

  test do
    system "#{bin}/pinax", "--help"
  end
end
