# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillctl < Formula
  desc "Manage agent skills, runtime projections, profiles, and MCP governance."
  homepage "https://github.com/yeisme/skillctl"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/skillctl/releases/download/v0.1.0/skillctl_0.1.0_darwin_amd64.tar.gz"
      sha256 "c9ca91467593cf0f3df845041a269125251a876834c7eca7dbae91abe427c6aa"

      def install
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/skillctl/releases/download/v0.1.0/skillctl_0.1.0_darwin_arm64.tar.gz"
      sha256 "ddcf8c880a04f46fb799278191c3c0afac6e5ed818a24803d51ee38ea23a5ca5"

      def install
        bin.install "skillctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/skillctl/releases/download/v0.1.0/skillctl_0.1.0_linux_amd64.tar.gz"
      sha256 "753b76e8f14d78b2cbf3468965b81bc6f3016cadf537f84353f8015e1a43ff4e"

      def install
        bin.install "skillctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/skillctl/releases/download/v0.1.0/skillctl_0.1.0_linux_arm64.tar.gz"
      sha256 "91a7cb03bce70558a18b3497e0ff7e9f8930cdb6893e4942469028c61c05f9e8"

      def install
        bin.install "skillctl"
      end
    end
  end

  test do
    system "#{bin}/skillctl", "--version"
  end
end
