# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskbridge < Formula
  desc "AI-assisted multi-provider task workflow CLI"
  homepage "https://github.com/yeisme/taskbridge"
  version "1.0.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.10/taskbridge_1.0.10_Darwin_x86_64.tar.gz"
      sha256 "4be3d668d4abe58817ae982c79ad5a1fdb4f1c048a8a53d3a3e561f6782b82ea"

    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.10/taskbridge_1.0.10_Darwin_arm64.tar.gz"
      sha256 "113e58dbe35a011aef21bea86bd0d499bf3b831deb8caf405c30df4feb098ff3"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.10/taskbridge_1.0.10_Linux_x86_64.tar.gz"
      sha256 "32981765f94762a7ef785717a5e8e923c2001c13b2e27340a1f2bcc36c934855"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.10/taskbridge_1.0.10_Linux_arm64.tar.gz"
      sha256 "1942f6a53bd681d4e8294c6983f48a39c15064336ac74aee7b1f589615aba680"
    end
  end

  def install
    bin.install "taskbridge"
  end

  test do
    system "#{bin}/taskbridge", "--help"
  end
end
