# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taskbridge < Formula
  desc "TaskBridge CLI for AI-assisted multi-provider task workflows."
  homepage "https://github.com/yeisme/taskbridge"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.6/taskbridge_Darwin_x86_64.tar.gz"
      sha256 "689f607b10b07299913e3fda23278a58b399099cdd764d503a9f377f1a55c1ca"

      def install
        bin.install "taskbridge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.6/taskbridge_Darwin_arm64.tar.gz"
      sha256 "6379bcbdf394eaebe627711b5d42372006e80f5303f5fafb55adab62b3035991"

      def install
        bin.install "taskbridge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.6/taskbridge_Linux_x86_64.tar.gz"
      sha256 "407db679d7ecc9e738aa0a4c096af925a2a7bb279cf7d3396f509460aec6ea7a"
      def install
        bin.install "taskbridge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yeisme/taskbridge/releases/download/v1.0.6/taskbridge_Linux_arm64.tar.gz"
      sha256 "ae6ba361a8392530f8f0b1af3bf4a59b08e6d6f7e8408df62bc3570de0332671"
      def install
        bin.install "taskbridge"
      end
    end
  end

  test do
    system "#{bin}/taskbridge", "--help"
  end
end
